In [1]:
import pandas as pd

In [8]:
def add_years_after_installation(df):
    # Convert date columns to datetime objects with only the date part
    df['InstallDate'] = pd.to_datetime(df['InstallDate']).dt.date
    df['CreationDate'] = pd.to_datetime(df['CreationDate']).dt.date

    # Calculate the number of years after installation
    df['YearsAfterInstallation'] = (df['CreationDate'] - df['InstallDate']).dt.days // 365

    return df

In [6]:
# Example usage:
# Load your dataset
df = pd.read_excel('dataset/DataFull.xlsx')
df.head()

,AssetID,AssetTypeID,Barcode,InstallDate,Capacity,AssetType,CallType,WorkDescription,ProblemType,Spend_ExGST,CompletionDate,CreationDate
0,258994,89,,1998-01-01,15.0,DUCTED SPLIT SYSTEM,Quotes,Ex Taste of Korea AC reactive,JOB COST,0.0,2023-08-02,2023-07-26
1,257871,10,0,2018-10-01,0.0,AIR FAN - EXHAUST,Quotes,General exhaust fan isolator i,JOB COST,0.0,2023-09-04,2023-08-23
2,257872,10,0,2018-10-01,0.0,AIR FAN - EXHAUST,Quotes,General exhaust fan isolator i,JOB COST,0.0,2023-09-04,2023-08-23
3,143943,89,1296,2003-08-05,1.2,DUCTED SPLIT SYSTEM,Quotes,LG- Heat Pump NO# 2 Repairs,JOB COST,0.0,2023-09-04,2023-08-18
4,143943,89,1296,2003-08-05,1.2,DUCTED SPLIT SYSTEM,Quotes,L17 Quorom Comms. Room PCB Rep,JOB COST,0.0,2023-06-22,2023-05-22

In [10]:
# Call the function to add the new column
updated_df = add_years_after_installation(df)

In [11]:
updated_df.head()

,AssetID,AssetTypeID,Barcode,InstallDate,Capacity,AssetType,CallType,WorkDescription,ProblemType,Spend_ExGST,CompletionDate,CreationDate,YearsAfterInstallation
0,258994,89,,1998-01-01,15.0,DUCTED SPLIT SYSTEM,Quotes,Ex Taste of Korea AC reactive,JOB COST,0.0,2023-08-02,2023-07-26,25.0
1,257871,10,0,2018-10-01,0.0,AIR FAN - EXHAUST,Quotes,General exhaust fan isolator i,JOB COST,0.0,2023-09-04,2023-08-23,4.0
2,257872,10,0,2018-10-01,0.0,AIR FAN - EXHAUST,Quotes,General exhaust fan isolator i,JOB COST,0.0,2023-09-04,2023-08-23,4.0
3,143943,89,1296,2003-08-05,1.2,DUCTED SPLIT SYSTEM,Quotes,LG- Heat Pump NO# 2 Repairs,JOB COST,0.0,2023-09-04,2023-08-18,20.0
4,143943,89,1296,2003-08-05,1.2,DUCTED SPLIT SYSTEM,Quotes,L17 Quorom Comms. Room PCB Rep,JOB COST,0.0,2023-06-22,2023-05-22,19.0

In [24]:
X = updated_df[['AssetTypeID','AssetType','YearsAfterInstallation','WorkDescription','Spend_ExGST']]
X

,AssetTypeID,AssetType,YearsAfterInstallation,WorkDescription,Spend_ExGST
0,89,DUCTED SPLIT SYSTEM,25.0,Ex Taste of Korea AC reactive,0.00
1,10,AIR FAN - EXHAUST,4.0,General exhaust fan isolator i,0.00
2,10,AIR FAN - EXHAUST,4.0,General exhaust fan isolator i,0.00
3,89,DUCTED SPLIT SYSTEM,20.0,LG- Heat Pump NO# 2 Repairs,0.00
4,89,DUCTED SPLIT SYSTEM,19.0,L17 Quorom Comms. Room PCB Rep,0.00
...,...,...,...,...,...
10826,238,VARIABLE AIR VOLUME UNITS,12.0,BASEMENT CHEMIST WAREHOUSE,352.60
10827,238,VARIABLE AIR VOLUME UNITS,12.0,CHEMIST WAREHOUSE INVEST WARM,131.50
10828,238,VARIABLE AIR VOLUME UNITS,13.0,Chemist Warehouse VAV-B1-1 Con,1837.92
10829,238,VARIABLE AIR VOLUME UNITS,12.0,AHU-4B1 ISSUES 100% RETAIL,120.67
10830,238,VARIABLE AIR VOLUME UNITS,12.0,CHEMIST WAREHOUSE INVEST WARM,131.50

In [23]:
print(updated_df.iloc[10:21])

    AssetID  AssetTypeID         Barcode InstallDate  Capacity  \
10   153284           15            1432  2000-11-09       0.1
11   153284           15            1432  2000-11-09       0.1
12   326331           53            1448  2013-08-18       0.0
13   326331           53            1448  2013-08-18       0.0
14   326335           63            1449  2013-08-18       0.0
15   326335           63            1449  2013-08-18       0.0
16   353289          117             01A  2006-01-01       0.0
17   353289          117             01A  2006-01-01       0.0
18   250039           89  22521000043700  2016-06-07      14.0
19   327724          172         2685913  2012-01-01      38.0
20   270750          239         3679463  2018-10-09      18.5

                         AssetType         CallType  \
10               AIR HANDLING UNIT  Time & Material
11               AIR HANDLING UNIT  Time & Material
12          CHILLER - WATER COOLED           Quotes
13          CHILLER - WATER COOLED           Quotes
14                   COOLING TOWER  Time & Material
15                   COOLING TOWER  Time & Material
16                     FIRE DAMPER           QUOTES
17                     FIRE DAMPER           Quotes
18             DUCTED SPLIT SYSTEM           Quotes
19  PACKAGED AIR CONDITIONING UNIT           Quotes
20            VARIABLE SPEED DRIVE  Time & Material

                   WorkDescription ProblemType  Spend_ExGST CompletionDate  \
10  Can I please get someone to lo         NaN       940.75     2022-12-22
11  review the Suzanne Grae tenanc         NaN         0.00     2023-10-20
12  Rust treatment main plant chil    JOB COST      2822.41     2022-11-11
13  MAIN PLANT CHILLER 1 &2 VIABRA    JOB COST      5799.19     2022-10-28
14            Check Main Plant RPZ         NaN         0.00     2023-11-30
15  Cooling Tower 1 & 2 loosing wa         NaN       255.96     2023-01-03
16  Gympie Central - Supply and In    JOB COST       376.84     2022-12-07
17  Gympie Central - Faulty Exhaus    JOB COST      1742.68     2022-09-20
18  Full Site Condenser Coil Clean    JOB COST         0.00     2024-01-16
19  QGB352570 - Now Healthy - Supp    JOB COST         0.00     2023-10-30
20            COOLING TOWER ALARMS         NaN         0.00     2023-04-14

   CreationDate  YearsAfterInstallation
10   2022-12-09                    22.0
11   2023-10-20                    22.0
12   2022-10-13                     9.0
13   2022-10-10                     9.0
14   2023-11-27                    10.0
15   2022-12-29                     9.0
16   2022-10-13                    16.0
17   2022-09-14                    16.0
18   2023-12-22                     7.0
19   2023-10-26                    11.0
20   2023-04-03                     4.0

In [25]:
X.to_csv('dataset/yearRecord.csv', index=False)

In [26]:
df = pd.read_csv('dataset/yearRecord.csv')
df

,AssetTypeID,AssetType,YearsAfterInstallation,WorkDescription,Spend_ExGST
0,89,DUCTED SPLIT SYSTEM,25.0,Ex Taste of Korea AC reactive,0.00
1,10,AIR FAN - EXHAUST,4.0,General exhaust fan isolator i,0.00
2,10,AIR FAN - EXHAUST,4.0,General exhaust fan isolator i,0.00
3,89,DUCTED SPLIT SYSTEM,20.0,LG- Heat Pump NO# 2 Repairs,0.00
4,89,DUCTED SPLIT SYSTEM,19.0,L17 Quorom Comms. Room PCB Rep,0.00
...,...,...,...,...,...
10826,238,VARIABLE AIR VOLUME UNITS,12.0,BASEMENT CHEMIST WAREHOUSE,352.60
10827,238,VARIABLE AIR VOLUME UNITS,12.0,CHEMIST WAREHOUSE INVEST WARM,131.50
10828,238,VARIABLE AIR VOLUME UNITS,13.0,Chemist Warehouse VAV-B1-1 Con,1837.92
10829,238,VARIABLE AIR VOLUME UNITS,12.0,AHU-4B1 ISSUES 100% RETAIL,120.67
10830,238,VARIABLE AIR VOLUME UNITS,12.0,CHEMIST WAREHOUSE INVEST WARM,131.50